install.packages("rmarkdown")
install.packages("tidyverse")
install.packages(c("matrixStats", "Hmisc", "splines", "foreach", "doParallel", "fastcluster", "dynamicTreeCut", "survival"))
source("http://bioconductor.org/biocLite.R")
biocLite(c("GO.db", "preprocessCore", "impute")) 
install.packages("BiocManager")
install.packages("WGCNA")
install.packages("igraph")
install.packages("arules")
install.packages("corrplot")
install.packages("rlist")
